<div class="col m-8-12 l-6-12 pb-large">
	<div class="newsletter">
		<form action="<?php echo $this->getFormActionUrl() ?>" method="post" class="newsletterForm">
			<input type="email" name="email" autocorrect="off" autocapitalize="off" placeholder="Enter your email to get updates">
			<input type="submit" name="submit" value="Signup"></form>		

			<div class="newsletter-message-box">
				<p></p>

				<div class="closeBtn">&times;</div>
			</div>
	</div>
</div>