	<div class="container footer">
		<div class="row pbb mt-pad">
			<div class="col m-8-12 l-8-12 pb-large">
				<div class="m-3-12 l-3-12 s-text-center m-text-center pb-large">
					<img src="/assets/img/evron-logo.svg" alt="Evron Food Store Logo" class="logo" width="170">
				</div>

				<div class="col m-9-12 l-9-12">
					<div class="col s-6-12 m-8-12">
						<!-- Footer About Links-->
						<ul class="col m-6-12">
							<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_about')->toHtml(); ?> 
						</ul>
						
						<!-- Footer Help Links-->
						<ul class="col m-6-12">
							<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_help')->toHtml(); ?> 
						</ul>
					</div>

					<div class="col s-6-12 m-4-12">
						<ul>
							<li><a href="#" title="Product Categories">Product Categories</a></li>
							<!-- List all product categories -->
							<?php $_helper = Mage::helper('catalog/category') ?>
							<?php $_categories = $_helper->getStoreCategories() ?>
							<?php $currentCategory = Mage::registry('current_category') ?>
							<?php if (count($_categories) > 0): ?>
						        <?php foreach($_categories as $_category): ?>
						            <li>
						                <a href="<?php echo $_helper->getCategoryUrl($_category) ?>" title="<?php echo $_category->getName() ?>">
						                    <?php echo $_category->getName() ?>
						                </a>
						            </li>
						        <?php endforeach; ?>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>

			<div class="col m-3-12 l-4-12 l-text-right s-text-center">	
				<a class="evron-wallet-icon" href="/evron-wallet"><span class="icon icon-wallet"></span>My Evron Wallet</a>	

				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_contact')->toHtml(); ?> 
			</div>
		</div>

		<div class="row mt-pad copyright">
			<p>&copy; 2015 Evron Foodstore Limited - All Rights Reserved</p>
		</div>
	</div>