<div class="container newsletter-social">
	<div class="row">
		<div class="col m-4-12 l-3-12 ml-text-right s-text-center">
			<h1 class="omega c-p">Be The first to save!&nbsp;&nbsp;</h1>
		</div>

		<!-- Newsletter -->
		<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>

		<div class="col m-12-12 l-3-12 end">
			<div class="socials sm-text-center l-text-right">
				<a href="https://twitter.com/evronfoodstore" title="Evron Food Store on twitter" class="icon icon-twitter" target="_blank"></a>
				<a href="https://www.facebook.com/EvronFoodStore" title="Evron Food Store on facebook" class="icon icon-facebook" target="_blank"></a>
				<a href="https://www.instagram.com/evronfoodstore/" title="Evron Food Store on Instagram" class="icon icon-instagram" target="_blank"></a>
			</div>
		</div>
	</div>
</div>