<div class="main-banner owl-carousel">
				<div>
					<img src="/assets/img/healthy-and-fresh.jpg" alt="Healthy and Fresh">
				</div>
			</div>

			<!-- Promotions -->
			<div class="promotion-carousel owl-carousel">
				<a href="fresh-meat-and-seafood" title="Fresh Meat &amp; Seafood">
					<img width="680" height="466" src="/assets/img/fresh-meat-and-seafood.jpg" alt="Fresh Meat &amp; Seafood">
				</a>

				<a href="fresh-meat-and-seafoo" title="Fresh Meat &amp; Seafood">
					<img width="680" height="466" src="/assets/img/menu-busters.jpg" alt="Fresh Meat &amp; Seafood">
				</a>

				<a href="fresh-meat-and-seafood" title="Fresh Meat &amp; Seafood">
					<img width="680" height="466" src="/assets/img/evron-value-basket.jpg" alt="Fresh Meat &amp; Seafood">
				</a>
			</div>

			<div class="pb-large s-hide">&nbsp;</div>

			<div class="featured-categories">
				<h1 class="omega c-p text-space-1 text-center mt-pad">SHOP FRESH FOOD, MEAT &amp; PANTRY GOODS</h1>

				<div class="row owl-carousel">
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/egusi-soup.jpg" alt="Egusi Soup">

						<h5>Soup Items</h5>
					</a>

					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/meat-fish-and-seafood.jpg" alt="Meat Fish and Seafood">
						<h5>Meat Fish &amp; Seafood</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/rice-and-pasta.jpg" alt="Rice and Pata">
						<h5>Rice and Pasta</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/tubers-and-plantain.jpg" alt="Tubers and Plantain">
						<h5>Tubers &amp; Plantain</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/breakfast-and-baking.jpg" alt="Breakfast &amp; Baking">
						<h5>Breakfast &amp; Baking</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/flours-and-grains.jpg" alt="Flours and Grains">
						<h5>Flours &amp; Grains</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/fruits-and-vegetables.jpg" alt="Fruits and Vegetables">
						<h5>Fruits &amp; Vegetables</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/dressings-and-tinned-goods.jpg" alt="Dressings and Tinned Goods">
						<h5>Dressings &amp; Tinned Goods</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/oils.jpg" alt="Oils">
						<h5>Oils</h5>
					</a>
					<a class="item" href="/" title="">
						<img width="190" height="190" src="/assets/img/spices-seasonings-and-condiments.jpg" alt="Spices Seasonings and Condiments">
						<h5>Spices, Seasonings &amp; Condiments</h5>
					</a>
				</div>
			</div>

			<div class="pb-large">&nbsp;</div><div class="pb-large s-hide">&nbsp;</div>