<!-- Payment options and security affirmation -->
<div class="container pb-large">
	<div class="row payment-methods mt-pad">
		<div class="col s-12-12 s-text-center end">
			<span class="payment-options">Payment Options</span><span><strong>Pay On Delivery</strong></span>
			<img src="/assets/img/visa-card.png" alt="Visa Card" height="30">&nbsp;<img src="/assets/img/mastercard.png" alt="MasterCard" height="30">
			<img src="/assets/img/verve-card.png" alt="Verve" height="30">

			<img src="/assets/img/comodo-seal.png" alt="Comodo Seal" class="security-seal">
		</div>
	</div>
</div>