<!-- Top Navigation Bar -->
<div class="container top-bar">
	<div class="row-main">
		<div class="left cycle-slideshow s-hide">FREE DELIVERY ON ALL ITEMS ABOVE N5000</div>

		<div class="links text-center right">
			<!-- <a href="/lists" title="Your List"><span class="icon icon-add-list"></span>Lists</a> -->

			<a href="/track-order" title="Track Your Order"><span class="icon icon-track"></span>Track Order</a>

			<a href="/help" title="Get Help"><span class="icon icon-help"></span>Help</a>

			<a href="tel:+23491073333"><span class="icon icon-call"></span>08091063333, 08091073333</a>
		</div>
	</div>
</div>