<!DOCTYPE html>
<html>
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body>
<!-- <div class="container">
	<?php echo $this->getChildHtml('global_notices'); ?>
</div> -->
<?php echo $this->getChildHtml('header') ?>

<?php echo $this->getChildHtml('content'); ?>

<!-- Footer -->
<?php echo $this->getChildHtml('footer_before'); ?>
<?php echo $this->getChildHtml('footer'); ?>
<?php echo $this->getChildHtml('before_body_end'); ?>
<?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>